# helm/trading-app/templates/configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: trading-app-config
data:
  DATABASE_URL: postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}
