# api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trading-app.name" . }}-api
  labels:
    {{- include "trading-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      {{- include "trading-app.selectorLabels" . | nindent 6 }}
      component: api
  template:
    metadata:
      labels:
        {{- include "trading-app.selectorLabels" . | nindent 8 }}
        component: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
            - name: APP_USERNAME
              value: "{{ .Values.api.username }}"
            - name: APP_PASSWORD
              value: "{{ .Values.api.password }}"
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
            - name: ASYNC_DATABASE_URL
              value: "postgresql+asyncpg://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
            - name: TRADIER_API_KEY
              value: "{{ .Values.brokers.tradier.apiKey }}"
            {{- if .Values.dashboard.ingress.tls.enabled }}
            - name: DASHBOARD_URL
              value: "https://{{ .Values.dashboard.ingress.host }}"
            {{- else }}
            - name: DASHBOARD_URL
              value: "http://{{ .Values.dashboard.ingress.host }}"
            {{- end }}
            - name: ETRADE_API_KEY
              value: "{{ .Values.brokers.etrade.apiKey }}"
            - name: TASTYTRADE_API_KEY
              value: "{{ .Values.brokers.tastytrade.apiKey }}"
          ports:
            - containerPort: {{ .Values.service.apiPort }}
          command: ["python"]
          args: ["main.py", "--mode", "api"]
