{{- if .Values.sync.enabled }}
# trading-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trading-app.name" . }}-order-manager
  labels:
    {{- include "trading-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "trading-app.selectorLabels" . | nindent 6 }}
      component: order-manager
  template:
    metadata:
      labels:
        {{- include "trading-app.selectorLabels" . | nindent 8 }}
        component: order-manager
    spec:
      containers:
        - name: order-manager
          image: "{{ .Values.trading.image.repository }}:{{ .Values.trading.image.tag }}"
          imagePullPolicy: {{ .Values.trading.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
            - name: TRADIER_API_KEY
              value: "{{ .Values.brokers.tradier.apiKey }}"
            - name: ALPACA_API_KEY
              value: "{{ .Values.brokers.alpaca.apiKey }}"
            - name: TASTYTRADE_USERNAME
              value: "{{ .Values.brokers.tastytrade.username }}"
            - name: TASTYTRADE_PASSWORD
              value: "{{ .Values.brokers.tastytrade.password }}"
            - name: KRAKEN_API_KEY
              value: "{{ .Values.brokers.kraken.apiKey }}"
            - name: KRAKEN_API_SECRET
              value: "{{ .Values.brokers.kraken.apiSecret }}"
            - name: TRADING_CONFIG_FILE
              value: "/etc/config/trade-config.yaml"
          command: ["python3"]
          args: ["main.py", "--mode", "manager", "--config", "/etc/config/trading-config.yaml"]
          volumeMounts:
            - name: trading-config-volume
              mountPath: /etc/config
      volumes:
        - name: trading-config-volume
          configMap:
            name: {{ include "trading-app.name" . }}-config
{{- end }}
