{{- if .Values.dashboard.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trading-dashboard-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  {{- if .Values.dashboard.ingress.tls.enabled }}
  tls:
  - hosts:
    {{- $host := regexReplaceAll "^[^.]+\\." "" .Values.dashboard.ingress.host }}
    {{- if $host }}
      - {{ $host }}
    {{- else }}
      - {{ .Values.dashboard.ingress.host }}
    {{- end }}
    secretName: {{ .Values.dashboard.ingress.tls.secretPrefix }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.dashboard.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: system-of-a-dow-dashboard
                port:
                  number: 8000
{{- end }}
---
{{- if .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trading-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  {{- if .Values.api.ingress.tls.enabled }}
  tls:
  - hosts:
    {{- $host := regexReplaceAll "^[^.]+\\." "" .Values.api.ingress.host }}
    {{- if $host }}
      - {{ $host }}
    {{- else }}
      - {{ .Values.api.ingress.host }}
    {{- end }}
    secretName: {{ .Values.api.ingress.tls.secretPrefix }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.api.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: system-of-a-dow-api
                port:
                  number: 8000
{{- end }}
