# helm/trading-app/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: trading-app-secret
type: Opaque
data:
  db-user: {{ .Values.database.user | b64enc }}
  db-password: {{ .Values.database.password | b64enc }}
  tradier-api-key: {{ .Values.brokers.tradier.apiKey | b64enc }}
  alpaca-api-key: {{ .Values.brokers.alpaca.apiKey | b64enc }}
