# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trading-app.name" . }}-api
  labels:
    {{- include "trading-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiPort }}
      protocol: TCP
      name: api
  selector:
    {{- include "trading-app.selectorLabels" . | nindent 4 }}
